name: Automerge dependabot updates

on: pull_request_target

jobs:
  dependabot-merge:
    name: Merge dependabot updates
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: z0rc/merge-pr-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOWED_UPDATE: any
          MERGE_METHOD: rebase
