name: Automerge dependabot updates

on:
  check_suite:
    types:
      - completed
  pull_request:
    branches:
      - master

jobs:
  merge-me:
    name: Merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - name: Merge dependabot updates
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: 'dependabot[bot]'
          MERGE_METHOD: REBASE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
